[package]
name = "pkg-skip"
version = "0.1.0"
publish = false

[dependencies]
pkg-lib = { version = "0.1.0", path = "../pkg-lib" }
clap = "^2"

[dev-dependencies.pkg-dev]
version = "0.1.0"
path = "../pkg-dev"